### ISSUE TITLE
LaTex格式常常出错

### ISSUE THREAD

**Issue by ZengJia-Notes** [MODCT/CeleryMath#1]
常常提示
Extra close brace or missing open brace
Missing \left or extra \right

请问要如何解决呢？

**Comment by rainyl** [comment]
请提供几个示例图片&期望输出&实际输出

**Comment by ZengJia-Notes** [comment]
感谢回复

### Extra close brace or missing open brace
**示例图片**
![extra](https://user-images.githubusercontent.com/55644002/183897721-0fbd4dfb-18e9-4054-b011-eccd79a40042.JPG)

**期望输出**
$J ( \pi ) = \mathbb { E } _ { p \left ( \ g \right ) } \mathbb { E } _ { p \left ( \tau | \pi , \mathbb { g } \right ) } \left [ \sum _ { L = 0 } ^ { T - 1 } \gamma ^ { t } r _ { L } \right ] ,$

**实际输出**
$J ( \pi ) = \mathbb { E } _ { p \left ( \ g \right ) } \mathbb { E } _ { p \left ( \tau \left | \pi , \mathbb { g } \right ) } \left [ \sum _ { L = 0 } ^ { T - 1 } \gamma ^ { t } r _ { L } \right ] ,$

### Missing \left or extra \right
**示例图片**
![missing left](https://user-images.githubusercontent.com/55644002/183897892-14d2b0a0-6718-46aa-8f74-e97c928876f4.JPG)

**期望输出**
$\mathbb { E } _ { d ^ { M } ( s , s ^ { \prime } ) } \left [ \left \| \nabla _ { \phi } D ( \phi ) | _ { \phi = ( \Phi ( s ) , \Phi ( s ^ { \prime } ) ) } \right \| ^ { 2 } \right ]$

**实际输出**
$\mathbb { E } _ { d ^ { M } ( s , s ^ { \prime } ) } \left [ \left \| \nabla _ { \phi } D ( \phi ) \right \| _ { \phi = ( \Phi ( s ) , \Phi ( s ^ { \prime } ) ) } \right \| ^ { 2 } \right ]$

**Comment by rainyl** [comment]
**TL;DR**
1. 尽量让公式清晰一点，如果源公式是低分辨率图片可以缩小
2. 如果比较熟悉LaTex公式语法，输出的公式可以手动微调一下
3. 多次尝试

**详细解释**
这个目前主要是图片尺寸的影响，因为模型训练的时候输入的是各种尺寸的，尺寸的影响会比较大，目前我还没有好的办法。
其次是贪婪搜索，目前我还没有太多的时间去完善，推理的时候使用beam search效果会更好。

另外，如果你对上述问题有解决方法或有能力完善，欢迎提PR，谢谢！
