### ISSUE TITLE
Hi, thank you for your work. I am studying formula recognition. I would like to study in depth whether can provide the code of the pythory model. Thank you very much

### ISSUE THREAD

**Issue by UUTTR9** [MODCT/CeleryMath#4]
Hi, thank you for your work. I am studying formula recognition. I would like to study in depth whether can provide the code of the pythory model. Thank you very much！

**Comment by rainyl** [comment]
OK, I didn't publish the models and training code with this GUI tool just because I'm so lazy...
I will collate and publish the backend recently, thanks for your advice :)

**Comment by UUTTR9** [comment]
Thank you for your reply and look forward to your next work!

**Comment by rainyl** [comment]
I have published the models and training codes at https://github.com/MODCT/Celery-LaTex-OCR , it's not complete for now and you can regard it as a `preview` version, I will add more details if needed, and if you have any questions, I'm willing to have a discussion 😄
