### ISSUE TITLE
Tokenizer.json  celeryMathEncoder.onnx  celeryMathDecoder.onnx

### ISSUE THREAD

**Issue by SWxEng** [MODCT/CeleryMath#5]
hi @MODCT

Where are the files for download  ???
Tokenizer.json
celeryMathEncoder.onnx  
celeryMathDecoder.onnx

**Comment by rainyl** [comment]
Sorry for my carelessness, you can download them from the first release at https://github.com/MODCT/CeleryMath/releases/tag/v0.1.0

**Comment by SWxEng** [comment]
Thank you

**Comment by rainyl** [comment]
Solved and no further problems, I am going to close this issue, have fun~
